## Colors configuration
colors:
  # Default colors
  primary:
    background: '#000000'
    foreground: '#ff0000'

  # Normal colors
  normal:
    black:   '#282C34'
    red:     '#6A0106'
    green:   '#8D0209'
    yellow:  '#AE0309'
    blue:    '#D2030D'
    magenta: '#F5040D'
    cyan:    '#E5131E'
    white:   '#460104'

  # Bright colors
  bright:
    black:   '#FA454C'
    red:     '#5E0F0B'
    green:   '#7D1611'
    yellow:  '#9B1A15'
    blue:    '#BC1F1A'
    magenta: '#DC251F'
    cyan:    '#ED3037'
    white:   '#3D0A07'
